theme: jekyll-theme-cayman

title: Goat Mountain Semiconductor Applications
description: Precision electronics, Mixed-signal design & integration, Semiconductor validation, Architecture, Medical & Scientific apps

plugins:
  - jekyll-seo-tag
