remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Essential for Minimal Mistakes to find your navigation
include: ["_data"]
title: "Goat Mountain Semiconductor"
name: "Theo Hatzis"
bio: "Senior Electronics Architect — 'Der Fuchs"
location: "Thames Valley / Munich"

author:
  name: "Theoharis (Theo) Hatzis"
  bio:  "Senior Electronics Architect — The Grace of Precision Semiconductor Testing"
  location: "UK & Germany"
  avatar: "/assets/images/Gemini_Generated_Image_q5u32zq5u32zq5u3.png"

  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile"





site_navigation: main 


permalink: /:title/
